### ISSUE TITLE
在Normalize和UnNormalize中是否存在错误？

### ISSUE THREAD

**Issue by lishaogang** [Giveupfree/SiamCAR-CAM#1]
你好，非常感谢你的代码，对我有很大的帮助。我修改了SiamCAR-CAM/CAM/GroupCAM.py中Normalize和UnNormalize，最终成功运行了你的代码，并且可以生成所有帧的heatmap，而不是如你博客中所说的只能生成部分heatmap。
1.关于Normalize
我直接运行你的代码会出现错误：

> `Traceback (most recent call last):
>   File "tools/CAM-demo.py", line 229, in <module>
>     main()
>   File "tools/CAM-demo.py", line 208, in main
>     outputs, img_crop, bbox = CAM(img, hp)
>   File "/home/pony/projects/demo/SiamCAR-CAM/CAM/GroupCAM.py", line 149, in __call__
>     return self.forward(input, class_idx, retain_graph)
>   File "/home/pony/projects/demo/SiamCAR-CAM/CAM/GroupCAM.py", line 104, in forward
>     norm_img = self.transform_norm(x_crop)
>   File "/home/pony/anaconda3/envs/siamcar-cam/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 166, in __call__
>     return F.normalize(tensor, self.mean, self.std, self.inplace)
>   File "/home/pony/anaconda3/envs/siamcar-cam/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 209, in normalize
>     raise TypeError('tensor is not a torch image.')
> TypeError: tensor is not a torch image.`

原因是在SiamCAR-CAM/CAM/GroupCAM.py的line 104：`norm_img = self.transform_norm(x_crop)`中，x_crop是(b,c,h,w)，torchision的Normalize仅接受(c,h,w)形状的输入。我包装了一个batch_Normalize后解决了该问题。

2.关于UnNormalize
你包装的UnNormalize的输入是tensor image of size (B,C,H,W)，但

> `for t, m, s in zip(tensor, self.mean, self.std):
>             t.mul_(s).add_(m)`

这个zip将tensor的B与std和mean的channel对应了，我修改了这个zip后，即可生成所有图片的heatmap
不知我理解的是否准确？

这是我的代码SiamCAR-CAM/CAM/GroupCAM.py

> class UnNormalize(object):
>     
>    def __init__(self, mean, std):
>         self.mean = mean
>         self.std = std
> 
>     def __call__(self, tensor):
>         """
>         Args:
>         :param tensor: tensor image of size (B,C,H,W) to be un-normalized
>         :return: UnNormalized image
>         """
>         # for t, m, s in zip(tensor, self.mean, self.std):
>         #     t.mul_(s).add_(m)
>         for t in tensor:
>             for c, s, m in zip(t, self.std, self.mean):
>                 t.mul_(s).add_(m)
>         tensor = tensor.clamp(min=0, max=1)
>         return tensor
> 
>
> class Normalize(object):
>     def __init__(self, mean, std):
>         self.mean = mean
>         self.std = std
>         self.Normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], inplace=True)
> 
>     def __call__(self, tensor):
>         """
>         Args:
>         :param tensor: tensor image of size (B,C,H,W) to be normalized
>         :return: Normalized image
>         """
>         norm_ts = []
>         for t in tensor:
>             # inplace 
>             self.Normalize(t)
> 
>         return tensor

**Comment by Giveupfree** [comment]
反归一化问题已经修复，torchvision的归一化是接受(B,C,H,W)的，这个可以从pytorch中的归一化部分对应的注释上是可以看到的

**Comment by Giveupfree** [comment]
针对归一化的问题，猜测可能是因为torchvision版本不同造成的，目前在代码中已经修复因为版本问题所造成的归一化和反归一化部分运行出错的现象

**Comment by lishaogang** [comment]
感谢回复。昨天我是按照requiremrnts.txt安装的依赖，torch版本是1.2.0,因此我也安装了较低版本的torchvision，我今天测试了较高版本的torchision，Normalize的输入是(B,C,H,W)
